257 checkbox component
UoaWDCC/uasc-web pull request #295
Opened 2024-04-25 14:20 UTC by zlrkw11

closes

2024-04-25 14:23 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/e1568d22-18e3-4e4e-8b01-d398663219b5)

2024-04-26 01:16 UTC, bcho892 requested changes
![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/c8d9e5e8-8f5a-44ac-8cca-aef5b4a4f3db)
The colours don't seem to quite match?

2024-04-26 01:16 UTC, bcho892 commented on client/src/components/generic/Checkbox/Checkbox.tsx
> +    <div {...props}>
the props should be spread on the `input`

2024-04-26 01:16 UTC, bcho892 commented on client/src/components/generic/Checkbox/Checkbox.tsx
> +type checkboxVariants = "default" | "checked" | "disabled"
nit: disabled should already be part of `React.InputHTMLAttributes<HTMLInputElement>`

2024-04-26 01:17 UTC, bcho892 commented
Might have to refer to figma again

2024-04-26 09:09 UTC, bcho892 requested changes

2024-04-26 09:09 UTC, bcho892 commented on client/src/components/generic/Checkbox/Checkbox.tsx
> +    <div {...props}>
we need to put this on the input component

2024-04-26 10:17 UTC, merged