320 booking info component
UoaWDCC/uasc-web pull request #334
Opened 2024-05-06 05:14 UTC by zlrkw11

closes #320

2024-05-06 05:14 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/a47a0e6f-6f1c-40a2-853d-0bf5fb83a424)

2024-05-06 05:22 UTC, bcho892 requested changes
![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/840533a0-df2b-4676-93eb-95a20e8b7c8c)

^ from the ticket

We shouldn't hard code the prices as they may change

2024-05-06 05:27 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/2606584c-179f-41bc-8f12-aca2bc9ce89b)
resolved the issue.

2024-05-06 05:39 UTC, bcho892 commented on client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
> +    <div className="border-gray-3 flex h-[474px] max-w-[347px] flex-col items-center rounded border">
this should be full width with content being centered on smaller screen so its responsive. height should be set to fit content with appropriate paddings

2024-05-06 05:39 UTC, bcho892 commented on client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
> +  price1: string
nit: these names aren't particularly descriptive

2024-05-06 05:39 UTC, bcho892 commented on client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
> +  <span className="bg-dark-blue-100 m-8 h-[1px] w-[283px]" />
again, not recommended to use fixed widths

2024-05-07 09:35 UTC, zlrkw11 commented on client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
> +  price1: string
done

2024-05-07 09:40 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/1c19d94d-72bb-416f-a373-eb15ea1748da)
- new small viewport 

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/eed4dc9e-685a-4cdc-abe8-ad90ec0242f3)
- largest desktop viewport

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/76acb398-bf37-4619-8578-5a421e37ed93)
- large mobile viewport

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/5bd5f1c2-010c-4892-b434-3d13ab9a411c)
- tablet viewport

2024-05-07 09:48 UTC, bcho892 approved these changes

2024-05-07 09:50 UTC, merged