Created success screen after user has made a booking
UoaWDCC/uasc-web pull request #340
Opened 2024-05-09 02:33 UTC by Kartik-M24

2024-05-09 02:34 UTC, Kartik-M24 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/161120979/e031f35b-ba61-42fb-b97a-6c03cd55acbc)
Small mobile view

2024-05-09 02:34 UTC, Kartik-M24 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/161120979/e594df18-3f82-41a2-8af3-9df936001866)

2024-05-09 02:37 UTC, Kartik-M24 commented
I haven't grabbed the dates as I was a bit unsure where I would import them from, is it from the data-layer?
I also wasn't sure what the bookings URL was for the button

2024-05-09 03:08 UTC, bcho892 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/c1c3b90a-2562-4247-a322-c2d44c7aaeb1)
Padding vertically seems a bit off, but gj on the mobile view! (IMO the container should have a smaller horizontal padding on smaller screens so it fills more). 

For the dates we'd likely make use of search params https://reactrouter.com/en/main/hooks/use-search-params to grab the dates (we will tell stripe to redirect to a page with those as the params)

2024-05-09 03:09 UTC, bcho892 commented
> I haven't grabbed the dates as I was a bit unsure where I would import them from, is it from the data-layer? I also wasn't sure what the bookings URL was for the button

Have a look at `routes.tsx`

2024-05-09 03:13 UTC, bcho892 commented on client/src/components/composite/SuccessfulBooking/SuccessfulBooking.tsx
> +      <div className=" xs:-top-72 relative mx-auto mb-48 h-auto w-10/12 rounded-sm border border-black bg-white px-2 py-2 md:w-6/12 lg:-mb-10">
I'd suggest having this full width to align with the heading

2024-05-11 09:30 UTC, bcho892 requested changes
Nice job on creating the components, now we should make this a subroute of the `bookings` route - have a look in the `Login` page to see how it was done with the password reset form, and refer to docs for [react router](https://www.robinwieruch.de/react-router-nested-routes/)

2024-05-11 09:30 UTC, bcho892 commented on client/src/pages/BookingSuccessComponent.tsx
> +const bookingSuccess = () => {
React components must be in `PascalCase`

2024-05-11 09:30 UTC, bcho892 commented on client/src/components/composite/SuccessfulBooking/SuccessfulBooking.tsx
> +  startDate: string | null
prefer the optional tag, as that handles both null and undefined
```suggestion
  startDate?: string
```

2024-05-11 09:30 UTC, bcho892 commented on client/src/pages/BookingSuccessComponent.tsx
nit: Probably could just call this file `BookingSuccess`

2024-05-20 11:56 UTC, Kartik-M24 commented
![Screenshot 2024-05-20 234905](https://github.com/UoaWDCC/uasc-web/assets/161120979/2ac3c1b0-0244-4460-93a9-dfdc9a30f4f7)

2024-05-20 12:04 UTC, bcho892 commented
there seems to be a bit of overflow on the page, we shouldn't have this on desktop

2024-05-20 13:57 UTC, bcho892 approved these changes
nit: next time branch off master so we don't get the garbage commits, you can technically fix this with cherry picking but it's better to avoid that (it's fine for this one)

2024-05-20 13:57 UTC, merged