333 tags component
UoaWDCC/uasc-web pull request #342
Opened 2024-05-09 12:31 UTC by zlrkw11

closes #333

2024-05-09 12:32 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/8368d401-fd08-4ee8-a7e8-2c3449365f72)
- normal tag (default displaying tag)

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/76ee3d6c-5134-4d84-b14e-a316a0635a0a)
- interactive tag (closing functionality implemented)

2024-05-09 23:40 UTC, bcho892 requested changes
Overall pretty clean, but for both tags we should allow the consumer to provide a handler for `onClick` and `onClose` so we can have custom functionality.

2024-05-09 23:40 UTC, bcho892 commented on client/src/components/generic/TagsComponent/TagsComponent.tsx
> +    setIsVisible(false)
gj on this one, another note tho can we let consumers pass in a custom handler like `onClose` type `() => void` (i.e we might be using this to display filters, and when we close one of the tags we want to remove the filter)

2024-05-09 23:40 UTC, bcho892 commented on client/src/components/generic/TagsComponent/TagsComponent.tsx
> +    <div className="bg-dark-blue-100 flex h-[32px] w-[80px] items-center justify-center overflow-hidden whitespace-nowrap rounded-full">
We should maybe have an `onClick` handler for this

2024-05-10 08:42 UTC, bcho892 approved these changes

2024-05-10 09:38 UTC, merged