310 about section component
UoaWDCC/uasc-web pull request #351
Opened 2024-05-12 23:58 UTC by zlrkw11

closes #310

2024-05-12 23:59 UTC, zlrkw11 commented
Left version
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/98cea998-cde5-4ad5-874d-697d8a149df3)
- large viewport
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/0a022823-c1f0-417e-a794-3c7b1f32872a)
- medium viewport
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/72187d20-86e0-4d34-80aa-bd08615f3552)
- small viewport

2024-05-13 00:01 UTC, zlrkw11 commented
Right version
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/95cda6d8-a6e3-4cd4-bdd2-6126078dd7cc)
- large viewport
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/26550ef7-de3c-47b6-98db-249465da4813)
- medium viewport
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/52347c8c-65f0-4e4f-8833-5f170b3471bc)
- small viewport

2024-05-13 00:06 UTC, zlrkw11 commented
There is a small issue that happens when we try to have transitions from LG to MD viewports. Texts do not fully show.

2024-05-13 01:11 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/886e2b1a-e73b-4e0f-a308-515063dd720d)
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/73d5840f-c3af-48ee-a02a-44149482203f)
- rounded corner now appears at the bottom, fits better (sm viewport)

2024-05-13 03:51 UTC, bcho892 requested changes
![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/271d995c-2079-4b84-b419-8b08b9ae0dd4)

Double check the border radiuses and colour

2024-05-13 03:54 UTC, bcho892 requested changes

2024-05-13 03:54 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +          <p className="lg:text-h2 text-dark-blue-100 ml-2 mr-2 mt-1 font-bold italic md:ml-2 md:mr-2 md:mt-1 lg:ml-8 lg:mr-8 lg:mt-4">
if its h2 we should not use `p`

2024-05-13 03:54 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +          <p className="lg:text-h2 text-dark-blue-100 ml-2 mr-2 mt-1 font-bold italic md:ml-2 md:mr-2 md:mt-1 lg:ml-8 lg:mr-8 lg:mt-4">
otherwise its incorrect semantically

2024-05-13 03:54 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +          </p>
You can extract the text into a helper component because they use the same styles

2024-05-13 10:33 UTC, bcho892 reviewed
Best to update the screenshots when you've updated the components

2024-05-13 10:33 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +  children: string
children is not the best name for this?

2024-05-14 05:46 UTC, zlrkw11 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +  children: string
fixed this issue by changing the name

2024-05-14 10:48 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/5754bfad-48e2-4dda-b232-19600253569e)
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/987fd895-48d0-43cc-a01f-0d45accdd559)
updated border color, implementing text styler component for both and adjusting spacing for both textboxes

2024-05-14 11:03 UTC, bcho892 commented
is there any reason the corners are sharp on the bottom edges?

2024-05-14 11:59 UTC, bcho892 approved these changes

2024-05-14 12:56 UTC, merged