374 restyle bank payment section
UoaWDCC/uasc-web pull request #378
Opened 2024-05-24 14:54 UTC by zlrkw11

closes #374

2024-05-24 14:56 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/83884e92-00ac-4a5a-9bc8-6acba1ef6480)
- default desktop view, i kept the part for 
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/3f400bff-d1dd-496d-9e66-10f5bd28e064)
(can remove if needed)

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/6db2d25a-1dcf-4145-905f-5765a5445bc3)
- mobile version

I assume title is waiting to be added when implemented

2024-05-24 14:59 UTC, zlrkw11 commented
I realized I forgot the copy button. Will implement it tommorow.

2024-05-24 22:46 UTC, bcho892 requested changes

2024-05-24 22:46 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +          <h4 className="">Transfer payment amount to bank number:</h4>
We should not be hard coding these, use the queries from before

2024-05-24 22:46 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> -  const { data } = useBankPaymentDetailsQuery()
Why are these being deleted?

2024-05-24 22:46 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> -  const { data } = useBankPaymentDetailsQuery()
They are required to pay for membership

2024-05-24 22:52 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +        <h4>1.</h4>
Should probably use an `ol` (ordered list) for this

2024-05-25 06:16 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/f52f1138-32eb-4623-875d-6af3247e6094)
- copy button made
- ordered list used (spacing fixed inside of it using tailwind)
- added back the price props

2024-05-25 06:17 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/a6d907be-539a-4d9e-ac3d-cf0d6692f614)
- mobile view

2024-05-25 06:18 UTC, zlrkw11 commented
notes: I wanna make mouse cursor to be default (not pointer) after the copy button is clicked.

2024-05-25 07:19 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +  const CopyButton = (text: any) => {
nit: gj on this but:
```suggestion
  const CopyButton = (text?: string) => {
```

2024-05-25 07:19 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +      navigator.clipboard.writeText(text)
and
```suggestion
  try {
    await navigator.clipboard.writeText(text);
  } catch (error) {
    console.error(error.message);
}
```
its asynchronous

2024-05-25 07:37 UTC, zlrkw11 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +      navigator.clipboard.writeText(text)
cheers bro

2024-05-25 07:58 UTC, bcho892 commented on client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
> +  const CopyButton = (text: any) => {
```suggestion
  const CopyButton = ({text}:{text?:string}) => {
```

2024-05-25 08:20 UTC, bcho892 approved these changes
Good job on figuring out the copy!

2024-05-25 08:22 UTC, bcho892 requested changes
![Screenshot_20240525-202127](https://github.com/UoaWDCC/uasc-web/assets/100653148/603cef41-91af-401e-9d6a-7c31f2a7aead)

Actually u may want to fix the order of this text, but otherwise looks good

2024-05-26 01:56 UTC, zlrkw11 commented
resolved

2024-05-26 02:21 UTC, bcho892 approved these changes

2024-05-26 07:30 UTC, merged