413 404 page
UoaWDCC/uasc-web pull request #422
Opened 2024-06-11 12:17 UTC by zlrkw11

closes #413

2024-06-11 12:18 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/79fb120a-c48b-4c19-8c6e-b3e9b525d6d8)
- set up route in router
- auto directs to the last page clicked

2024-06-11 12:29 UTC, bcho892 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/c0fccebf-c4d6-4ccc-923a-42bbf96b7dc7)

can we center this vertically? in this case its fine to use screen height

2024-06-11 12:30 UTC, bcho892 requested changes

2024-06-11 12:30 UTC, bcho892 commented on client/src/pages/404.tsx
> +// import React from "react"
do not comment out unused code, need to delete it

2024-06-11 12:30 UTC, bcho892 commented on client/src/pages/404.tsx
> +    window.history.go(-1)
we should navigate back to home page, also should use `react-router` functions for this instead (prefer to redirect to home)

2024-06-11 12:30 UTC, bcho892 commented on client/src/pages/404.tsx
> +      <div className="pt-[2.5%]">
nit: percentage margins not preferred

2024-06-12 04:18 UTC, zlrkw11 commented on client/src/pages/404.tsx
> +      <div className="pt-[2.5%]">
changed to px

2024-06-12 04:32 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/0855d5bd-5a50-4a29-aa32-fe920eff39d8)
- content centered vertically
- react-router implemented
- comments deleted

2024-06-12 04:35 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/09055f6c-ac35-436f-8283-3960fe52f2d9)
- mobile viewport

2024-06-12 04:36 UTC, bcho892 commented
The image quality is very bad, can we use an svg instead?

2024-06-12 04:55 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/47ba22de-6dfa-4c9a-8bde-8a19bc6df8f8)
- new svg imported

2024-06-12 05:16 UTC, bcho892 approved these changes

2024-06-12 05:29 UTC, merged