443 add link for guest member
UoaWDCC/uasc-web pull request #471
Opened 2024-06-20 07:30 UTC by zlrkw11

closes #443

2024-06-20 07:31 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/169e3c84-07f5-4fc4-bdd2-bddfa39d023d)
- link added (customized light-blue-100 as its colour for user experience)

2024-06-20 07:35 UTC, bcho892 approved these changes

2024-06-20 07:35 UTC, bcho892 commented on client/src/pages/Profile/Profile.tsx
> +                      userMembership === "Admin" ? (
Nit: admin does not need to know it's end of year

2024-06-20 07:37 UTC, bcho892 requested changes
https://github.com/UoaWDCC/uasc-web/issues/451#is
![Screenshot_20240620-193624](https://github.com/UoaWDCC/uasc-web/assets/100653148/4c006844-a3bf-4a16-b699-28b120d17441)

2024-06-22 09:13 UTC, bcho892 approved these changes

2024-06-24 07:59 UTC, merged