364 about page
UoaWDCC/uasc-web pull request #496
Opened 2024-06-22 08:48 UTC by zlrkw11

closes #364

2024-06-22 08:50 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/29cdabbd-4fae-4ad4-b8e7-039a1cdbd049)
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/ebe47ee0-12db-43b8-a463-679278e3c483)
- small viewport

2024-06-22 08:52 UTC, zlrkw11 commented
I replaced the old images with new ones I found on UASC facebook because the resolution was too low for testing purposes. It will be responsive so we should change the images according to figma design once those photos are provided (not screenshots).

2024-06-22 08:53 UTC, zlrkw11 commented
I have also decided to cancel the overlapping design on the textbox. It makes the webpage glitch a lot and making it hard to style.
Now the textbox will stay under the image for both md and lg viewports.

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/a97830c0-7b29-49b9-a9d6-739d3514b51c)
- md viewport

![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/6628bbfc-315f-4b3a-bbc6-9629bf5b466f)
- lg viewport

2024-06-22 09:05 UTC, bcho892 commented
> I have also decided to cancel the overlapping design on the textbox. It makes the webpage glitch a lot and making it hard to style. Now the textbox will stay under the image for both md and lg viewports.
> 
> ![image](https://private-user-images.githubusercontent.com/64724157/341956440-a97830c0-7b29-49b9-a9d6-739d3514b51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDczNjQsIm5iZiI6MTcxOTA0NzA2NCwicGF0aCI6Ii82NDcyNDE1Ny8zNDE5NTY0NDAtYTk3ODMwYzAtN2IyOS00OWI5LWE5ZDYtNzM5ZDM1MTRiNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNTIyMGExYjMwODE0YWY3MGFhNGY3Y2FkMjNkMjcwMTdlZTExZWVhNzVjZjkzMzExNmU4ZGFjNGQxOTc1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbcEbL1PPs3gEz6SCAsUbR6QXcw0NgNaA1nh_J7ol9Y)
> 
> * md viewport
> 
> ![image](https://private-user-images.githubusercontent.com/64724157/341956454-6628bbfc-315f-4b3a-bbc6-9629bf5b466f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDczNjQsIm5iZiI6MTcxOTA0NzA2NCwicGF0aCI6Ii82NDcyNDE1Ny8zNDE5NTY0NTQtNjYyOGJiZmMtMzE1Zi00YjNhLWJiYzYtOTYyOWJmNWI0NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxODA0N2RhYTNmZGY2NWQ4ZjU3YmU5MTU2MWZhN2VlMTE1YTUyZTI2Mjc5NzRjMGJkOWNlNGM1NTY2YWZiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wWXPzQhi6G7j01iywNK5_BwLVlxJk4T1TN6jX7nkMvI)
> 
> * lg viewport

That is fine to not make them overlapping, however, I'd prefer you to instead put them side by side as we are wasting a lot of space right now

2024-06-22 09:08 UTC, bcho892 requested changes

2024-06-22 09:08 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
>  type Props = IAboutProps
`IAboutProps` is a confusing name, should name it after the component

2024-06-22 09:08 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +          <TextStyler title={title} text={text} />
What text? Name could be more descriptive

2024-06-22 09:17 UTC, bcho892 commented on client/src/components/generic/AboutSection/AboutSection.tsx
> +          className="relative w-full rounded-t-lg md:h-[500px] md:w-[900px]"
your images are stretching and changing aspect ratio, look into https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit `object-fit: cover`

2024-06-23 09:11 UTC, bcho892 commented
Can we set a max width for the page (900-1000px is probably good), also prefer text to be vertically centered:

![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/ac802f74-ea35-4203-ba62-c6cb9e38cf04)

2024-06-23 09:13 UTC, bcho892 commented
this image gets stretched on larger screens:

![image](https://github.com/UoaWDCC/uasc-web/assets/100653148/dc10df7f-80a0-4bdf-bdc5-2da1db64b588)

2024-06-23 10:11 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/e848b6e4-0782-4f05-964a-5f01ae94e3ee)
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/ac4efb01-cf46-428e-b1e1-6a9871f79bdf)
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/3a93055e-ad8c-49ad-9f4a-df5787650396)
- responsive for 3 viewports
- right section conditionally renders
- space used increased
- styling improved
- left and right sections adjusted to stay same in styling

2024-06-23 10:23 UTC, bcho892 approved these changes

2024-06-23 12:08 UTC, merged