427 edit profile pop up
UoaWDCC/uasc-web pull request #509
Opened 2024-06-25 11:00 UTC by zlrkw11

closes #427 

onEdit function waiting to be implemented for the sumbit button.

2024-06-25 11:05 UTC, bcho892 requested changes

2024-06-25 11:05 UTC, bcho892 commented on client/src/components/composite/Profile/ProfileEdit/ProfileEdit.tsx
> +  if (!closed) {
dont handle it in here, should be controlled outside the component (can just pass in an `onClose` and `isOpen`)

2024-06-25 11:05 UTC, bcho892 commented on client/src/components/composite/Profile/ProfileEdit/ProfileEdit.story.tsx
> +        { fieldName: "date_of_birth", defaultFieldValue: "2004/06/09" },
nit: this will break the input, need a separate transformer for dates etc (probably not in this ticket tho)

2024-06-25 11:05 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/3d85625a-14fd-4976-aed6-2ac47dd39d03)
- normal view

https://github.com/UoaWDCC/uasc-web/assets/64724157/b4c5467f-9866-4e86-ba30-1a1cdd46c07e
- closing button

2024-06-26 00:47 UTC, bcho892 approved these changes

2024-06-26 01:10 UTC, merged