Created endpoint to allow admins to add coupon to user.
UoaWDCC/uasc-web pull request #527
Opened 2024-06-27 07:08 UTC by AzizPatel786

2024-06-27 08:04 UTC, bcho892 requested changes
Just some small changes

2024-06-27 08:04 UTC, bcho892 commented on server/src/service-layer/controllers/AdminController.ts
> +      for (let i = 0; i < quantity; i++) {
Create an array of promises then use promise.all

2024-06-27 08:04 UTC, bcho892 commented on server/src/business-layer/services/StripeService.ts
> +      const stripe = new Stripe(process.env.STRIPE_API_KEY)
Stripe is already declared as a global

2024-06-28 22:28 UTC, bcho892 commented on server/src/service-layer/controllers/AdminController.ts
> +      for (let i = 0; i < quantity; i++) {
This isn't needed anymore

2024-06-28 22:28 UTC, bcho892 commented on server/src/service-layer/controllers/AdminController.ts
> +      const couponPromises = Array.from({ length: quantity }, () =>
This isn't a promise, need to make it async
```suggestion
      const couponPromises = Array.from({ length: quantity }, async () =>
```

2024-06-28 22:28 UTC, bcho892 commented on server/src/service-layer/controllers/AdminController.ts
> +        stripeService.addCouponToUser(user.stripe_id, amount)
```suggestion
       await stripeService.addCouponToUser(user.stripe_id, amount)
```

2024-06-29 02:50 UTC, AzizPatel786 commented on server/src/service-layer/controllers/AdminController.ts
> +      for (let i = 0; i < quantity; i++) {
Sorry forgot to remove it

2024-06-29 02:55 UTC, bcho892 approved these changes

2024-06-29 02:58 UTC, merged