515 frontend display note saying the lodge and booking opening dates
UoaWDCC/uasc-web pull request #561
Opened 2024-06-29 09:27 UTC by zlrkw11

closes #515

2024-06-29 09:28 UTC, zlrkw11 commented
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/c35d29aa-02a1-4914-bd24-9141f8f6e229)

2024-06-29 09:48 UTC, bcho892 approved these changes
Can you add a todo comment saying to remove it

2024-06-29 10:08 UTC, bcho892 requested changes

2024-06-29 10:08 UTC, bcho892 commented on client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
> +          className={`flex max-w-[381px] flex-col items-center gap-2 ${ProtectedCreateBookingSection ? "blur-sm" : "blur-none"} `}
what is this supposed to do?

2024-07-02 08:50 UTC, bcho892 approved these changes

2024-07-02 09:10 UTC, merged