572 frontend add link for user to reset password on profile page
UoaWDCC/uasc-web pull request #578
Opened 2024-07-02 09:09 UTC by zlrkw11

closes #572

2024-07-07 06:10 UTC, bcho892 requested changes
wrong folder, this needs to be done in `uasc-next` as per #592

2024-07-09 10:35 UTC, bcho892 commented
There seems to be too many files changed

2024-07-10 05:29 UTC, asun555 commented
> There seems to be too many files changed

2024-07-10 09:25 UTC, bcho892 approved these changes

2024-07-10 09:29 UTC, merged