added message when user logged into their account
UoaWDCC/uasc-web pull request #766
Opened 2024-08-26 04:04 UTC by zlrkw11

![image](https://github.com/user-attachments/assets/b0d59cd9-93b9-4ede-9fd4-81e897297e38)

2024-08-26 04:24 UTC, bcho892 reviewed
The PR says

2024-08-26 04:24 UTC, bcho892 commented on client/src/components/composite/LoginForm/LoginForm.tsx
> +      alert("Logging In...")
we want something to display under the button, not an alert (which blocks everyting)

2024-08-26 06:37 UTC, zlrkw11 commented
Easy, I wanted to make a component but thought alert was needed

On Mon, Aug 26, 2024, 4:24 PM Benson Cho ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> The PR says
> ------------------------------
>
> In client/src/components/composite/LoginForm/LoginForm.tsx
> <https://github.com/UoaWDCC/uasc-web/pull/766#discussion_r1730643781>:
>
> > @@ -57,6 +57,7 @@ const LoginForm = ({
>      if (isLoading || !loginHandler) return
>      try {
>        setIsLoading(true)
> +      alert("Logging In...")
>
> we want something to display under the button, not an alert (which blocks
> everyting)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UoaWDCC/uasc-web/pull/766#pullrequestreview-2259699032>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APNZZPJEZHIYAKH2SHG2LTLZTKUXRAVCNFSM6AAAAABNDGJGCCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENJZGY4TSMBTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-26 09:36 UTC, zlrkw11 commented
https://github.com/user-attachments/assets/1794f6c8-6661-4b92-bcc5-324bceecebcb

2024-08-26 10:51 UTC, zlrkw11 commented
https://github.com/user-attachments/assets/7b7e6d19-a4e6-4789-a22a-62d171360ecd

updated

2024-08-27 02:47 UTC, bcho892 approved these changes

2024-08-27 02:47 UTC, bcho892 commented on client/src/components/composite/LoginForm/LoginForm.tsx
> +        ) : null}
```suggestion
        {isLoading && (
          <p className="text-dark-blue-100 absolute mt-4">Logging in...</p>
        )}
```

2024-08-27 02:48 UTC, bcho892 requested changes
shouldn't be absolute, causes styling problems

2024-08-27 03:57 UTC, bcho892 approved these changes

2024-08-27 04:08 UTC, merged