783 backend write a cron job to automatically update a google sheet with the members
UoaWDCC/uasc-web pull request #791
Opened 2024-10-04 11:32 UTC by jeffplays2005

Still semi-draft...

*. Update dependencies in server workspace
* Create new script in `package.json`
* Created new cron job(note that the cron is currently disabled and has workflow-dispatch for now).
* Create `fetchUsers` method that fetches users from the backend
* Create `getAllUsers` that fetches all the users from the backend using `fetchUsers`
* Create `authenticateGoogle` method that returns a google auth client
  * Note that documentation will come soon...
* Create `appendToGoogleSheet` and `clearSheet`
  * `appendToGoogleSheet` takes in the logs and auth client and updates the google sheet rows
  * `clearSheet` clears the google sheet so that `appendToGoogleSheet` doesn't overlap everything

>[!Note] 
The logic is still somewhat rough and could have improvements. Quite a lot of duplicate code and possibly better ways to update the google sheet instead of just appending and clearing every time.

2024-10-04 23:58 UTC, bcho892 requested changes

2024-10-04 23:58 UTC, bcho892 commented on server/package.json
> +    "googleapis": "^144.0.0",
should this be a dev dependency?

2024-10-04 23:58 UTC, bcho892 commented on server/tooling/update-google-sheet-members.ts
> +  getAllUsers(token)
this should be done synchronously

2024-10-04 23:58 UTC, bcho892 commented on server/tooling/update-google-sheet-members.ts
> +  const token = args[0]
its better to generate the token in this script rather than the workflow

2024-10-04 23:58 UTC, bcho892 commented on .github/workflows/update_google_sheet_members.yml
> +  NEXT_PUBLIC_BACKEND_BASE_URL: ${{secrets.VITE_BACKEND_BASE_URL}}
you are missing the service account env variable

2024-10-04 23:58 UTC, bcho892 commented on server/tooling/update-google-sheet-members.ts
> +  const token = args[0]
https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk, and also refer to how a token is made in https://github.com/UoaWDCC/uasc-web/blob/master/server/tooling/login-prod.ts#L34

2024-10-05 02:46 UTC, jeffplays2005 commented
Added some documentation in here:

https://github.com/UoaWDCC/uasc-web/wiki/Deployment-Information#google-sheet-members-action

2024-10-05 03:54 UTC, bcho892 reviewed
have you tested the function by running `ts-node` locally?

2024-10-05 03:54 UTC, bcho892 commented on server/tooling/update-google-sheet-members.ts
> +  return allUsers
do we fetch all users and not check if they're members?

2024-10-05 09:19 UTC, jeffplays2005 commented
> have you tested the function by running `ts-node` locally?
>
> do we fetch all users and not check if they're members?
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/94d4ce20-8187-4135-9f88-b6cd8eca6be7">

2024-10-05 09:20 UTC, jeffplays2005 commented
Note that I'll need to document more on the wiki as the `GOOGLE_SERVICE_ACCOUNT_JSON` doesn't work for this... the `GOOGLE_SERVICE_ACCOUNT_JSON` only has access for firebase I believe although this use case needs an account json for sheets

2024-10-05 09:32 UTC, bcho892 approved these changes

2024-10-05 10:32 UTC, jeffplays2005 commented
For documentation in this branch:

Updated secrets

<img width="789" alt="Screenshot 2024-10-05 at 11 31 35 PM" src="https://github.com/user-attachments/assets/4c905918-2ae3-410d-8aa8-331028a6c699">

2024-10-05 10:32 UTC, merged