806 frontend refine events component according to figma
UoaWDCC/uasc-web pull request #807
Opened 2024-10-12 09:58 UTC by zlrkw11

goon

2024-10-12 09:58 UTC, zlrkw11 commented
![image](https://github.com/user-attachments/assets/2d110cd8-83bd-4910-b244-947987acfcc1)

2024-10-12 09:59 UTC, zlrkw11 commented
![image](https://github.com/user-attachments/assets/9880d32d-88f0-4dab-8d78-ad3c307217f5)

2024-10-12 10:00 UTC, zlrkw11 commented
- image added
- props adjusted 
- storybook check for stacked components

2024-10-12 10:06 UTC, bcho892 requested changes
follow [proper guidelines](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#provide-context-and-guidance) for a PR description so future contributors can determine the purpose

2024-10-12 10:06 UTC, bcho892 commented on client/src/assets/images/test.png
delete this and use an url instead

2024-10-13 04:09 UTC, bcho892 approved these changes

2024-10-13 04:38 UTC, merged